pipeline:
  name: Build python
  identifier: Build_mydeentesla_python_1705289589010
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Python App
                  identifier: build_python_app
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI" python -m pip install --upgrade pip pip install  pytest if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: mydeentesla/python
        build: <+input>
